$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), 'lib'))


guard 'rspec' do
  watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec" }
end

